apply plugin: 'com.android.library'
apply from: '../base_module.gradle'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

android {
    namespace 'dev.olog.service.floating'
    defaultConfig {
        consumerProguardFiles 'consumer-rules.pro'
    }

    //kotlinOptions.allWarningsAsErrors = true

}

apply from: '../kapt.gradle'

dependencies {
    implementation project(':core')
    implementation project(':injection')
    implementation project(':image-provider')
    implementation project(':shared-android')
    implementation project(':shared')
    implementation project(':shared-widgets')
    implementation project(':prefs-keys')
    implementation project(':media')
    implementation project(':offline-lyrics')
    implementation project(':data')
    implementation project(':analytics')
    implementation project(':equalizer')

    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android
    implementation libs.dagger
    kapt libs.dagger.compiler

    implementation libs.androidx.core.ktx
    implementation libs.androidx.media
    implementation libs.androidx.lifecycle.runtime
    implementation libs.androidx.lifecycle.extensions
    implementation libs.androidx.lifecycle.java8

    implementation libs.androidx.constraintlayout
    implementation libs.androidx.appcompat
    implementation libs.google.material
    implementation libs.androidx.recyclerview


    implementation libs.glide
}
