plugins {
    id("dev.msc.library")
    id("dev.msc.hilt")
    id("dev.msc.compose")
}

android {
    namespace = "dev.olog.service.floating"
    buildFeatures {
        viewBinding = true
    }
}

dependencies {
    implementation project(':core')
    implementation project(':image-provider')
    implementation project(':shared-android')
    implementation project(':shared')
    implementation project(':shared-widgets')
    implementation project(':shared-compose')
    implementation project(':prefs-keys')
    implementation project(':media')
    implementation project(':offline-lyrics')

    implementation(libs.androidx.core)
    implementation(libs.androidx.media)
    implementation(libs.androidx.lifecycle.runtime)
    implementation(libs.androidx.lifecycle.service)
    implementation(libs.androidx.lifecycle.java8)

    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.material)
    implementation(libs.androidx.recycler)

    implementation(libs.glide)
}
