apply plugin: 'kotlin-android'

android {

    compileSdkVersion libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        minSdkVersion libs.versions.minSdk.get().toInteger()
        targetSdkVersion libs.versions.targetSdk.get().toInteger()
        versionCode libs.versions.versionCode.get().toInteger()
        versionName libs.versions.versionName.get()

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            debuggable false
        }

        debug {
//            debuggable false
        }
    }

    flavorDimensions "version"
    productFlavors {
        mock {
            dimension "version"
        }
        full {
            dimension "version"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    useLibrary 'android.test.runner'

    useLibrary 'android.test.base'
    useLibrary 'android.test.mock'

}

dependencies {
    implementation libs.kotlin.stdlib
    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android
    testImplementation libs.kotlinx.coroutines.test
    testImplementation project (':test-shared')
    androidTestImplementation project (':test-shared')

    // Core library
    testImplementation libs.junit
    testImplementation libs.mockito.android
    testImplementation libs.mockito.kotlin

    androidTestImplementation libs.mockito.android
    androidTestImplementation libs.mockito.kotlin
    androidTestImplementation libs.androidx.test.core
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.test.junit
}
