// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        google()
    }

    dependencies {
        classpath libs.android.gradle.plugin
        classpath libs.kotlin.gradle.plugin
        classpath libs.google.services.plugin
        classpath libs.firebase.crashlytics.plugin
        classpath libs.hilt.gradle.plugin
    }


    
    
}

allprojects {
    gradle.projectsEvaluated { // TODO remove after coroutines became stable
        tasks.withType(org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile).all {
            kotlinOptions.freeCompilerArgs += ["-opt-in=kotlinx.coroutines.FlowPreview"]
            kotlinOptions.freeCompilerArgs += ["-opt-in=kotlinx.coroutines.ExperimentalCoroutinesApi"]
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
