include ':app', ':core', ':presentation', ':shared-android', ':data', ':image-provider', ':prefs-keys', ':jaudiotagger', ':media', ':app-shortcuts', ':service-music', ':service-floating', ':offline-lyrics', ':test-shared', ':intents', ':shared', ':shared-widgets', ':equalizer'
include ':shared-compose'

// todo add these as git submodules

// checkout tags/r2.19.1
gradle.ext.exoplayerModulePrefix = 'exoplayer-'
apply from: new File('/Users/eugeniu.olog/dev/ExoPlayer', 'core_settings.gradle')