plugins {
    id("canaree.android.library")
    id("canaree.hilt")
    id("kotlin-kapt")
}

android {
    namespace 'dev.olog.service.music'
    defaultConfig {
        consumerProguardFiles 'consumer-rules.pro'
    }

    //kotlinOptions.allWarningsAsErrors = true

}

dependencies {
    implementation project(':app-shortcuts')
    implementation project(':jaudiotagger')
    implementation project(':core')
    implementation project(':image-provider')
    implementation project(':shared-android')
    implementation project(':shared')
    implementation project(':prefs-keys')
    implementation project(':intents')
    implementation project(':equalizer')
    implementation project(':data')

    implementation libs.androidx.media
    implementation libs.androidx.lifecycle.runtime
    implementation libs.androidx.lifecycle.java8
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.lifecycle.service

    implementation libs.glide

    implementation libs.last.fm.binding


    implementation 'com.google.android.exoplayer:exoplayer-core:2.13.3'
//    implementation project(':exoplayer-library-core')
//    implementation project(':exoplayer-extension-flac')
//    implementation project(':exoplayer-extension-opus')
//    implementation project(':exoplayer-extension-ffmpeg')
}
