plugins {
    id("dev.msc.library")
    id("dev.msc.hilt")
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

android {
    namespace = "dev.olog.service.music"
}

dependencies {
    implementation project(':app-shortcuts')
    implementation project(':core')
    implementation project(':image-provider')
    implementation project(':shared-android')
    implementation project(':shared')
    implementation project(':prefs-keys')
    implementation project(':intents')
    implementation project(':equalizer')

    implementation(libs.androidx.media)
    implementation(libs.androidx.lifecycle.runtime)
    implementation(libs.androidx.lifecycle.service)
    implementation(libs.androidx.lifecycle.java8)

    implementation(libs.glide)


//    implementation 'com.google.android.exoplayer:exoplayer-core:2.10.4'
    implementation project(':exoplayer-library-core')
    implementation project(':exoplayer-extension-flac')
    implementation project(':exoplayer-extension-opus')
    implementation project(':exoplayer-extension-ffmpeg')
}
