package dev.olog.data.folder

import dev.olog.core.entity.MostPlayedSong
import dev.olog.core.entity.track.Folder
import dev.olog.core.entity.track.Song

// TODO for some reason is not autogenerated
data class Folders_view(
    val directory: String,
    val songs: Long,
    val date_added: Long,
)

internal fun Folders_view.toDomain() = Folder(
    directory = directory,
    songs = songs.toInt()
)


internal fun SelectMostPlayed.toDomain() = MostPlayedSong(
    song = Song(
        id = id,
        artistId = author_id,
        albumId = collection_id,
        title = title,
        artist = author,
        albumArtist = album_artist,
        album = collection,
        duration = duration,
        dateAdded = date_added,
        directory = directory,
        path = path,
        discNumber = disc_number,
        trackNumber = track_number,
        idInPlaylist = 0, // TODO remove
        isPodcast = is_podcast,
    ),
    counter = counter.toInt(),
)