package dev.olog.data.folder

import dev.olog.core.entity.MostPlayedSong
import dev.olog.core.folder.Folder
import dev.olog.core.MediaUri
import dev.olog.core.track.Song

// TODO for some reason is not autogenerated
data class Folders_view(
    val directory: String,
    val songs: Long,
    val date_added: Long,
)

internal fun Folders_view.toDomain() = Folder(
    uri = MediaUri(
        source = MediaUri.Source.MediaStore,
        category = MediaUri.Category.Folder,
        id = directory,
        isPodcast = false,
    ),
    directory = directory,
    songs = songs.toInt()
)


internal fun SelectMostPlayed.toDomain() = MostPlayedSong(
    song = Song(
        uri = MediaUri(
            source = MediaUri.Source.MediaStore,
            category = MediaUri.Category.Track,
            id = id,
            isPodcast = false,
        ),
        artistUri = MediaUri(
            source = MediaUri.Source.MediaStore,
            category = MediaUri.Category.Author,
            id = author_id,
            isPodcast = false,
        ),
        albumUri = MediaUri(
            source = MediaUri.Source.MediaStore,
            category = MediaUri.Category.Collection,
            id = collection_id,
            isPodcast = false,
        ),
        title = title,
        artist = author,
        albumArtist = album_artist,
        album = collection,
        duration = duration,
        dateAdded = date_added,
        directory = directory,
        path = path,
        discNumber = disc_number,
        trackNumber = track_number,
        idInPlaylist = 0, // TODO remove
    ),
    counter = counter.toInt(),
)