plugins {
    id("canaree.android.library")
}

android {
    namespace 'dev.olog.test.shared'
}

dependencies {
    implementation libs.kotlinx.coroutines.test
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.junit
}
