plugins {
    id("dev.msc.library")
    id("dev.msc.hilt")
    id("dev.msc.compose")
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

android {
    namespace = "dev.olog.presentation"
    buildFeatures {
        viewBinding = true
    }
}

dependencies {
    implementation project(':app-shortcuts')
    implementation project(':core')
    implementation project(':image-provider')
    implementation project(':shared-android')
    implementation project(':shared-widgets')
    implementation project(':shared-compose')
    implementation project(':prefs-keys')
    implementation project(':media')
    implementation project(':offline-lyrics')
    implementation project(':jaudiotagger')
    implementation project(':intents')
    implementation project(':shared')
    implementation project(':equalizer')

    implementation(libs.scrollhelper)
    implementation(libs.glide)

    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.material)
    implementation(libs.androidx.core)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.palette)
    implementation(libs.androidx.media)
    implementation(libs.androidx.browser)
    implementation(libs.androidx.preference)
    implementation(libs.androidx.coordinator)
    implementation(libs.androidx.fragments)

    implementation(libs.lottie)
    implementation(libs.taptargetview)

    implementation(libs.dialogs.core)
    implementation(libs.dialogs.color)
    implementation(libs.customtabs)
    implementation(libs.colordesaturation)

    implementation(libs.androidx.lifecycle.runtime)
    implementation(libs.androidx.lifecycle.java8)
    implementation(libs.androidx.lifecycle.viewmodel)

    // TODO try remove
    implementation(libs.compose.material)
}
