plugins {
    id("canaree.android.library")
    id("canaree.hilt")
    id("kotlin-android-extensions")
}

android {
    namespace 'dev.olog.presentation'
    defaultConfig {
        consumerProguardFiles 'consumer-rules.pro'
    }

//    kotlinOptions.allWarningsAsErrors = true

}

androidExtensions {
    experimental = true
}

dependencies {
    implementation project(':app-shortcuts')
    implementation project(':core')
    implementation project(':injection')
    implementation project(':image-provider')
    implementation project(':shared-android')
    implementation project(':shared-widgets')
    implementation project(':prefs-keys')
    implementation project(':media')
    implementation project(':offline-lyrics')
    implementation project(':jaudiotagger')
    implementation project(':intents')
    implementation project(':shared')
    implementation project(':equalizer')
    implementation project(':data')

    implementation libs.dagger
    kapt libs.dagger.compiler

    implementation libs.scroll.helper
    implementation libs.glide

    implementation libs.androidx.appcompat
    implementation libs.androidx.activity
    implementation libs.google.material
    implementation libs.androidx.core.ktx
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.palette
    implementation libs.androidx.media
    implementation libs.androidx.browser
    implementation libs.androidx.preference
    implementation libs.androidx.coordinatorlayout
    implementation libs.androidx.fragment

    implementation libs.lottie
    implementation libs.tap.target.view

    implementation libs.dagger.android
    implementation libs.dagger.android.support
    kapt libs.dagger.android.processor

    implementation libs.material.dialogs.core
    implementation libs.material.dialogs.color
    implementation libs.color.desaturation

    implementation libs.last.fm.binding

    implementation libs.androidx.lifecycle.runtime
    implementation libs.androidx.lifecycle.extensions
    implementation libs.androidx.lifecycle.java8
    implementation libs.androidx.lifecycle.viewmodel.ktx
}
