package dev.olog.data.collection

import dev.olog.core.entity.track.Album

// TODO for some reason is not autogenerated
data class Albums_view(
    val id: Long,
    val author_id: Long,
    val title: String,
    val author: String,
    val songs: Long,
    val directory: String,
    val dateAdded: Long
)

// TODO for some reason is not autogenerated
data class Podcast_collections_view(
    val id: Long,
    val author_id: Long,
    val title: String,
    val author: String,
    val songs: Long,
    val directory: String,
    val dateAdded: Long
)

internal fun Albums_view.toDomain() = Album(
    id = id,
    artistId = author_id,
    title = title,
    artist = author,
    songs = songs.toInt(),
    directory = directory,
    isPodcast = false,
)

internal fun Podcast_collections_view.toDomain() = Album(
    id = id,
    artistId = author_id,
    title = title,
    artist = author,
    songs = songs.toInt(),
    directory = directory,
    isPodcast = true,
)