plugins {
    id("canaree.android.library")
}

android {
    namespace 'dev.olog.media'
    //kotlinOptions.allWarningsAsErrors = true

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    implementation project(':core')
    implementation project(':shared-android')
    implementation project(':intents')
    implementation project(':shared')

    implementation libs.androidx.media
    implementation libs.androidx.appcompat
    implementation libs.androidx.lifecycle.livedata.ktx
}
