plugins {
    id("canaree.android.library")
    id("canaree.hilt")
}

android {
    namespace 'dev.olog.appshortcuts'
    //kotlinOptions.allWarningsAsErrors = true
}

dependencies {
    implementation project(":localisation")
    implementation project(':core')
    implementation project(':image-provider')
    implementation project(':intents')

    implementation libs.androidx.core
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat

    implementation libs.glide
}