apply plugin: 'com.android.library'
apply from: '../base_module.gradle'

android {
    namespace 'dev.olog.appshortcuts'
    //kotlinOptions.allWarningsAsErrors = true
}

dependencies {
    implementation project(':core')
    implementation project(':image-provider')
    implementation project(':intents')

    implementation libs.androidx.core
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat

    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android

    implementation libs.glide
}