plugins {
    id("dev.msc.library")
}

android {
    namespace = "dev.olog.appshortcuts"
}

dependencies {
    implementation project(':core')
    implementation project(':image-provider')
    implementation project(':intents')

    implementation(libs.androidx.core)
    implementation(libs.androidx.appcompat)
    implementation(libs.glide)
}