plugins {
    id("canaree.android.library")
}

android {
    namespace 'dev.olog.shared.android'
    defaultConfig {
        consumerProguardFiles 'consumer-rules.pro'
    }

    //kotlinOptions.allWarningsAsErrors = true
}

dependencies {
    implementation project(':prefs-keys')

    implementation libs.google.material
    implementation libs.androidx.core.ktx
    implementation libs.androidx.palette
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.preference

    // google architecture components
    implementation libs.androidx.lifecycle.runtime
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.livedata.ktx
}
