plugins {
    id("canaree.android.library")
    id("canaree.hilt")
}

android {
    namespace 'dev.olog.core'
    defaultConfig {
        consumerProguardFiles 'consumer-rules.pro'
    }

    //kotlinOptions.allWarningsAsErrors = true
}

dependencies {
    implementation project(':shared')

    implementation libs.dagger
    kapt libs.dagger.compiler

    implementation libs.androidx.annotation
}
