plugins {
    id("canaree.android.application")
    id("canaree.hilt")
    id("kotlin-android-extensions")
    id("com.google.gms.google-services")
    id("com.google.firebase.crashlytics")
}

android {
    namespace 'dev.olog.msc'
    defaultConfig {
        applicationId "dev.olog.msc"
    }

    buildTypes {
        release {
            minifyEnabled true
//            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ".debug"
        }
    }
}


dependencies {
    implementation project(':app-shortcuts')
    implementation project(':core')
    implementation project(':data')
    implementation project(':image-provider')
    implementation project(':injection')
    implementation project(':media')
    implementation project(':prefs-keys')
    implementation project(':presentation')
    implementation project(':shared-android')
    implementation project(':shared-widgets')
    implementation project(':service-music')
    implementation project(':service-floating')
    implementation project(':offline-lyrics')
    implementation project(':intents')
    implementation project(':shared')
    implementation project(':equalizer')

    // google architecture components
    implementation libs.androidx.lifecycle.runtime
    implementation libs.androidx.lifecycle.extensions
    implementation libs.androidx.lifecycle.java8
    implementation libs.androidx.lifecycle.viewmodel.ktx

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.browser
    implementation libs.androidx.preference

    // dagger
    implementation libs.dagger
    kapt libs.dagger.compiler
    implementation libs.dagger.android
    implementation libs.dagger.android.support
    kapt libs.dagger.android.processor

    // debug
    debugImplementation libs.leak.canary

    // firebase
    implementation libs.firebase.core
    implementation libs.firebase.crashlytics
}