plugins {
    id("dev.msc.app")
    id("dev.msc.hilt")
    alias(libs.plugins.crashlytics)
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}


android {
    namespace = "dev.olog.msc"
    defaultConfig {
        applicationId "dev.olog.msc"

        buildConfigField 'String', "LAST_FM_KEY", localProperties.last_fm_key
    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ".debug"
        }
    }

    buildFeatures {
        buildConfig = true
    }
}

dependencies {
    implementation project(':app-shortcuts')
    implementation project(':core')
    implementation project(':data')
    implementation project(':image-provider')
    implementation project(':media')
    implementation project(':prefs-keys')
    implementation project(':presentation')
    implementation project(':shared-android')
    implementation project(':shared-widgets')
    implementation project(':service-music')
    implementation project(':service-floating')
    implementation project(':offline-lyrics')
    implementation project(':intents')
    implementation project(':shared')

    // google architecture components
    implementation(libs.androidx.lifecycle.runtime)
    implementation(libs.androidx.lifecycle.process)
    implementation(libs.androidx.lifecycle.java8)
    implementation(libs.androidx.lifecycle.viewmodel)

    implementation(libs.androidx.core)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.browser)
    implementation(libs.androidx.preference)
    implementation(libs.glide)
    implementation(libs.customtabs)

    debugImplementation(libs.leakcanary)
    implementation(libs.firebase.crashlytics)
}