package dev.olog.data.author

import dev.olog.core.entity.track.Artist

// TODO for some reason is not autogenerated
data class Artists_view(
    val id: Long,
    val name: String,
    val songs: Long,
    val dateAdded: Long,
    val directory: String,
)

// TODO for some reason is not autogenerated
data class Podcast_authors_view(
    val id: Long,
    val name: String,
    val episodes: Long,
    val dateAdded: Long,
    val directory: String,
)

internal fun Artists_view.toDomain() = Artist(
    id = id,
    name = name,
    songs = songs.toInt(),
    isPodcast = false
)

internal fun Podcast_authors_view.toDomain() = Artist(
    id = id,
    name = name,
    songs = episodes.toInt(),
    isPodcast = true
)