plugins {
    id("dev.msc.library")
}

android {
    namespace "dev.olog.shared.widgets"
}

dependencies {
    implementation project(':prefs-keys')
    implementation project(':shared-android')
    implementation project(':shared')
    implementation project(':core')

    implementation(libs.androidx.material)
    implementation(libs.androidx.core)
    implementation(libs.androidx.palette)
}
