plugins {
    id("canaree.android.library")
    id("canaree.hilt")
    id("kotlin-kapt")
}

android {
    namespace 'dev.olog.data'
    defaultConfig {
        consumerProguardFiles 'consumer-rules.pro'

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [
                        "room.schemaLocation"  : "$projectDir/schemas".toString(),
                        "room.incremental"     : "true",
                        "room.expandProjection": "true"
                ]
            }
        }
    }

    sourceSets {
        androidTest.assets.srcDirs += files("$projectDir/schemas".toString())
    }

//    kotlinOptions.allWarningsAsErrors = true
}

dependencies {
    implementation project(':core')
    implementation project(':shared')
    implementation project(':prefs-keys')

    implementation libs.dagger
    kapt libs.dagger.compiler

    implementation libs.androidx.core.ktx
    implementation libs.androidx.preference
    implementation libs.androidx.lifecycle.extensions

    implementation libs.fuzzywuzzy
    implementation libs.gson
    implementation libs.retrofit
    implementation libs.retrofit.gson
    implementation libs.okhttp
    implementation libs.okhttp.logging

    implementation libs.sql.content.resolver
    implementation libs.room.runtime
    implementation libs.room.ktx
    kapt libs.room.compiler

}
