plugins {
    id("org.jetbrains.kotlin.plugin.compose")
}

apply plugin: 'com.android.library'
apply from: '../base_module.gradle'

android {
    namespace 'dev.olog.shared.compose'

    buildFeatures {
        compose = true
    }
}

dependencies {
    implementation(project(":core"))
    implementation(project(":image-provider"))
    implementation(project(":shared"))
    implementation(project(":shared-android"))
    implementation(project(":shared-widgets"))
    implementation(project(":media"))

    implementation platform(lib_compose.bom)
    implementation(lib_compose.foundation)
    implementation(lib_compose.material)
    implementation(lib_compose.material_icons)
    implementation(lib_compose.tooling_preview)
    debugImplementation(lib_compose.tooling)
    debugImplementation(lib_compose.pooling_container)

    implementation lib_ui.glide
}