plugins {
    id("dev.msc.library")
    id("dev.msc.compose")
}

android {
    namespace 'dev.olog.shared.compose'
}

dependencies {
    implementation(project(":core"))
    implementation(project(":image-provider"))
    implementation(project(":shared"))
    implementation(project(":shared-android"))
    implementation(project(":shared-widgets"))
    implementation(project(":media"))

    implementation(lib_compose.material)
    implementation lib_ui.glide
    implementation lib_x.material
}