apply plugin: 'com.android.library'
apply from: '../base_module.gradle'
apply plugin: 'kotlin-kapt'

android {
    namespace 'dev.olog.offlinelyrics'
    defaultConfig {
        consumerProguardFiles 'consumer-rules.pro'
    }

    //kotlinOptions.allWarningsAsErrors = true

}

dependencies {
    implementation project(':core')
    implementation project(':shared-android')
    implementation project(':shared')
    implementation project(':jaudiotagger')
    implementation project(':intents')

    implementation libs.dagger
    kapt libs.dagger.compiler
    implementation libs.kotlinx.coroutines.core

    implementation libs.androidx.appcompat
    implementation libs.google.material
    implementation libs.androidx.core
    implementation libs.androidx.core.ktx
}