plugins {
    id("canaree.android.library")
    id("canaree.hilt")
}

android {
    namespace 'dev.olog.image.provider'
    defaultConfig {
        consumerProguardFiles 'consumer-rules.pro'
    }

    //kotlinOptions.allWarningsAsErrors = true

}

dependencies {
    implementation project(':jaudiotagger')
    implementation project(':core')
    implementation project(':shared-android')
    implementation project(':shared')
    implementation project(':injection')
    implementation project(':prefs-keys')
    implementation project(':intents')
    implementation project(':data')
    implementation project(':equalizer')

    implementation libs.dagger
    kapt libs.dagger.compiler

    implementation libs.color.desaturation
    implementation libs.glide
    kapt libs.glide.compiler
    // mandatory for glide 4.9.0 or below compatibility
    kapt libs.android.support.annotations

    implementation libs.androidx.core.ktx
    implementation libs.androidx.preference
}
