plugins {
    id("dev.msc.library")
    id("dev.msc.hilt")
}

android {
    namespace = "dev.olog.image.provider"
}

dependencies {
    implementation project(':jaudiotagger')
    implementation project(':core')
    implementation project(':shared-android')
    implementation project(':shared')
    implementation project(':prefs-keys')
    implementation project(':intents')

    implementation(libs.colordesaturation)
    implementation(libs.glide)
    kapt(libs.glide.processor)

    implementation(libs.androidx.core)
    implementation(libs.androidx.preference)
}
