apply plugin: 'com.android.library'
apply from: '../base_module.gradle'
apply plugin: 'kotlin-kapt'

apply from: '../kapt.gradle'

android {
    namespace 'dev.olog.equalizer'
}

dependencies {
    implementation project(':core')

    implementation libs.dagger
    kapt libs.dagger.compiler
    implementation libs.androidx.annotation
}
