package dev.olog.data.genre

import dev.olog.core.entity.MostPlayedSong
import dev.olog.core.entity.track.Artist
import dev.olog.core.entity.track.Genre
import dev.olog.core.entity.track.Song

// TODO for some reason is not autogenerated
data class Genres_view(
    val id: Long,
    val name: String,
    val songs: Long,
)

internal fun Genres_view.toDomain() = Genre(
    id = id,
    name = name,
    songs = songs.toInt(),
)

internal fun Genres_playables_view.toDomain() = Song(
    id = id,
    artistId = author_id,
    albumId = collection_id,
    title = title,
    artist = author,
    albumArtist = album_artist,
    album = collection,
    duration = duration,
    dateAdded = date_added,
    directory = directory,
    path = path,
    discNumber = disc_number,
    trackNumber = track_number,
    idInPlaylist = 0, // TODO remove
    isPodcast = false,
)

internal fun SelectRelatedArtists.toDomain() = Artist(
    id = author_id,
    name = author,
    songs = songs.toInt(),
    isPodcast = false
)

internal fun SelectMostPlayed.toDomain() = MostPlayedSong(
    song = Song(
        id = id,
        artistId = author_id,
        albumId = collection_id,
        title = title,
        artist = author,
        albumArtist = album_artist,
        album = collection,
        duration = duration,
        dateAdded = date_added,
        directory = directory,
        path = path,
        discNumber = disc_number,
        trackNumber = track_number,
        idInPlaylist = 0, // TODO remove
        isPodcast = is_podcast,
    ),
    counter = counter.toInt(),
)